// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqxnobmnrppbhocsydvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxeG5vYm1ucnBwYmhvY3N5ZHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODU0NjEsImV4cCI6MjA2ODI2MTQ2MX0.abRllWCtYDV2IVeHF2r2vd1EmmsEqIoAEhCVEdDKHZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});